// <auto-generated />
using System;
using DeliverCompany.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeliverCompany.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240926084228_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeliverCompany.Models.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverID"));

                    b.Property<decimal>("BeloppIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BeloppUt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CarReg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleEmployee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalBeloppIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBeloppUt")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DriverID");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            DriverID = 1,
                            BeloppIn = 500.00m,
                            BeloppUt = 200.00m,
                            CarReg = "ABC123",
                            DriverName = "Alice Smith",
                            NoteDate = new DateTime(2024, 9, 25, 10, 42, 27, 927, DateTimeKind.Local).AddTicks(2163),
                            NoteDescription = "Completed delivery route",
                            ResponsibleEmployee = "John Doe",
                            TotalBeloppIn = 500.00m,
                            TotalBeloppUt = 200.00m
                        },
                        new
                        {
                            DriverID = 2,
                            BeloppIn = 0.00m,
                            BeloppUt = 100.00m,
                            CarReg = "XYZ789",
                            DriverName = "Bob Johnson",
                            NoteDate = new DateTime(2024, 9, 24, 10, 42, 27, 927, DateTimeKind.Local).AddTicks(2210),
                            NoteDescription = "Vehicle maintenance",
                            ResponsibleEmployee = "Admin User",
                            TotalBeloppIn = 0.00m,
                            TotalBeloppUt = 100.00m
                        });
                });

            modelBuilder.Entity("DeliverCompany.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "admin@example.com",
                            Name = "Admin User",
                            Password = "admin123",
                            Role = "Admin"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "john@example.com",
                            Name = "John Doe",
                            Password = "password123",
                            Role = "Employee"
                        });
                });

            modelBuilder.Entity("DeliverCompany.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<decimal>("BeloppIn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BeloppUt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventID");

                    b.HasIndex("DriverID");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            EventID = 1,
                            BeloppIn = 400.00m,
                            BeloppUt = 50.00m,
                            DriverID = 1,
                            NoteDate = new DateTime(2024, 9, 25, 10, 42, 27, 927, DateTimeKind.Local).AddTicks(2228),
                            NoteDescription = "Delivered goods to customer"
                        },
                        new
                        {
                            EventID = 2,
                            BeloppIn = 0.00m,
                            BeloppUt = 300.00m,
                            DriverID = 2,
                            NoteDate = new DateTime(2024, 9, 24, 10, 42, 27, 927, DateTimeKind.Local).AddTicks(2231),
                            NoteDescription = "Vehicle repaired"
                        },
                        new
                        {
                            EventID = 3,
                            BeloppIn = 0.00m,
                            BeloppUt = 100.00m,
                            DriverID = 1,
                            NoteDate = new DateTime(2024, 9, 23, 10, 42, 27, 927, DateTimeKind.Local).AddTicks(2233),
                            NoteDescription = "Picked up supplies"
                        });
                });

            modelBuilder.Entity("DeliverCompany.Models.Event", b =>
                {
                    b.HasOne("DeliverCompany.Models.Driver", "Driver")
                        .WithMany("Events")
                        .HasForeignKey("DriverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DeliverCompany.Models.Driver", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
